export { default as TodolistMockup } from "../Shots/Todolist.jpg"
export { default as AwsWorkshopMockup } from "../Shots/AwsWorkshop.png"
export { default as WarehouseMockup } from "../Shots/Warehouse.svg"
export { default as BlogTranslationMockup } from "../Shots/BlogTranslation.svg"
export { default as IeltsMockup } from "../Shots/Ielts.svg"
