export { default as TodolistLogo } from "./TodolistLogo.svg"
export { default as AwsWorkshopLogo } from "./AwsWorkshopLogo.svg"
export { default as WarehouseLogo } from "./WarehouseLogo.svg"
export { default as BlogTranslationLogo } from "./BlogTranslationLogo.svg"
export { default as IeltsLogo } from "./IeltsLogo.svg"
