export { default as TodolistShot } from "./Todolist.jpg"
export { default as AwsWorkshopShot } from "./AwsWorkshop.png"
export { default as WarehouseShot } from "./Warehouse.svg"
export { default as BlogTranslationShot } from "./BlogTranslation.svg"
export { default as IeltsShot } from "./Ielts.svg"
